#!/usr/bin/env zsh
export EDITOR=/opt/homebrew/bin/nvim
export PATH=$PATH:/opt/homebrew/bin
export PATH=$PATH:~/.local/bin

export XDG_DATA_HOME=$HOME/.local/share
export XDG_CONFIG_HOME=$HOME/.config
export XDG_STATE_HOME=$HOME/.local/state
export XDG_CACHE_HOME=$HOME/.cache

# no noise
setopt NO_BEEP

# History option

export SAVHIST=1000 # on disk
export HISTSIZE=1050 # in memory

setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST



DOTFILE_PATH=~/code/dotfiles
ZSH_FOLDER_PATH="$DOTFILE_PATH/zsh"

# Turn on auto-completions
fpath=( "$ZSH_FOLDER_PATH/functions" "${fpath[@]}" )
fpath=( "$ZSH_FOLDER_PATH/completions" $fpath)

autoload -Uz compinit && compinit

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward

# turn on colors for ls command
export LSCOLORS=exfxcxdxbxegedabagacad
export CLICOLOR=1
alias ls='ls -G'

# Setup up your prompt

set_vcs_prompt(){
  vcs_info

  is_git=$(git rev-parse --is-inside-work-tree 2>/dev/null)
  if [[ "$is_git" == "true" ]]; then
    if ! git diff --quiet; then
      vcs_prompt="%F{red}(${vcs_info_msg_0_})%f"
      prompt_symbol="ಠ_ಠ"
    elif ! git diff --cached --quiet; then
      vcs_prompt="%F{white}(${vcs_info_msg_0_})%f"
      prompt_symbol="(^ω^)"
    else
      vcs_prompt="%F{green}(${vcs_info_msg_0_})%f"
      prompt_symbol="(｡•̀ᴗ-)✧"
    fi
  else
    vcs_prompt=""
    prompt_symbol="$"
  fi
}


autoload -Uz add-zsh-hook
autoload -Uz vcs_info

add-zsh-hook precmd set_vcs_prompt

zstyle ':vcs_info:git:*' formats '%b'
# allow more than one 'vcs_info_msg_X_' string as defined by the formats style
zstyle ':vcs_info:*' max-exports 3

autoload -Uz read_csco

set_csco_prompt(){
  CSCO=$(read_csco)
}

add-zsh-hook precmd set_csco_prompt

setopt PROMPT_SUBST
PROMPT='%F{cyan}%~%f %F{yellow}$CSCO%f $vcs_prompt %(?.%F{green}✔.%F{red}✖)%f $prompt_symbol '

